const $=s=>document.querySelector(s),app=$('#app'),params=new URLSearchParams(location.search),hash=new URLSearchParams(location.hash.slice(1));
const API_BASE=(window.KANDO_CONFIG?.apiBase||'').replace(/\/$/,'');
const pageURL=q=>new URL('./'+q,location.href).href;
function apiURL(path){if(!API_BASE&&location.hostname.endsWith('github.io'))throw Error('A játékszerver összekötése még folyamatban van.');return API_BASE+'/api/'+path}
const icons=['◈','✦','◉','⬡','▣','⌘'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rosterPage=0;
let view=params.get('view')||'join',code=params.get('code')||'',token='',admin=sessionStorage.getItem('kando-nyiltnap-admin')||'',state,renderKey='',polling=false,task={},chosenAvatar=0;
if(admin){sessionStorage.setItem('kando-nyiltnap-admin',admin);history.replaceState(null,'',location.pathname+location.search)}
if(view==='host'){const old=JSON.parse(sessionStorage.getItem('kando-nyiltnap-host')||'null');if(old){code=old.code;token=old.token}}
if(view==='join'){const old=JSON.parse(sessionStorage.getItem('kando-nyiltnap-player')||'null');if(old){code=old.code;token=old.token;view='player'}}
$('#full').onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch{notify('A böngésző teljes képernyős módját is használhatod.')}};
function notify(text){$('#notice').textContent=text;$('#notice').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').hidden=true,4500)}
async function api(path,data){let r;try{r=await fetch(apiURL(path),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})}catch{throw Error('Megszakadt a kapcsolat. Ellenőrizd a Wi-Fi-t, majd próbáld újra!')}const j=await r.json();if(!r.ok){if(r.status===401&&view==='host'){admin='';sessionStorage.removeItem('kando-nyiltnap-admin');hostStart()}throw Error(j.error||'Nem sikerült a művelet.');}return j}
function bind(sel,fn){const el=$(sel);if(el)el.onclick=async()=>{try{await fn()}catch(e){notify(e.message)}}}
function art(){return '<div class="circuit-art" aria-hidden="true"><div class="art-node">⌘</div><i class="art-wire"></i><div class="art-node">◈</div><i class="art-wire"></i><div class="art-node">↗</div></div>'}
function entry(){app.innerHTML=`<section class="entry"><div><p class="eyebrow">NYÍLT NAP / KANDÓ ÉLMÉNYLABOR</p><h1>A jövő nem vár.<br><em>Kapcsolódj be!</em></h1><p class="intro">Köss be egy hálózatot. Programozz egy robotot. Találd meg a hibát. A következő megoldás a te kezedben van.</p>${art()}<div class="facts"><div><b>3</b>küldetés</div><div><b>6–8 perc</b>első próbakör</div><div><b>1 csapatnyi</b>új ötlet</div></div></div><form id="join-form" class="card"><p class="eyebrow">A KIVETÍTŐN MÁR VÁR A KÓD</p><h2>Belépek a játékba</h2><label for="code">Játékkód</label><input id="code" class="code-input" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="000 000" required autocomplete="off" value="${esc(code)}"><label for="name">Hogyan szerepelj a ranglistán?</label><input id="name" maxlength="18" placeholder="Beceneved" autocomplete="off" required><label>Válassz jelvényt!</label><div class="avatars">${icons.map((x,i)=>`<button type="button" aria-label="${i+1}. jelvény" aria-pressed="${i===chosenAvatar}" data-avatar="${i}" class="${i===chosenAvatar?'selected':''}">${x}</button>`).join('')}</div><button class="primary submit">Mehet a küldetés →</button><p class="demo-note">Nincs regisztráció. A tanár indítja a közös játékot.</p></form></section>`;
document.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{chosenAvatar=+b.dataset.avatar;document.querySelectorAll('[data-avatar]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b)})});
$('#join-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('.submit');button.disabled=true;try{const r=await api('join',{code:$('#code').value,name:$('#name').value,avatar:chosenAvatar});code=r.code;token=r.token;sessionStorage.setItem('kando-nyiltnap-player',JSON.stringify(r));view='player';renderKey='';await poll()}catch(err){notify(err.message)}finally{button.disabled=false}}}
function hostStart(){if(!admin){app.innerHTML=`<section class="waiting"><form id="teacher-login" class="card"><p class="eyebrow">TANÁRI IRÁNYÍTÓPULT</p><h1>Üdv újra!</h1><label for="teacher-password">Tanári jelszó</label><input id="teacher-password" type="password" autocomplete="current-password" required><button class="primary" style="margin-top:20px">Belépés →</button></form></section>`;$('#teacher-login').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const r=await api('login',{password:$('#teacher-password').value});admin=r.token;sessionStorage.setItem('kando-nyiltnap-admin',admin);hostStart()}catch(err){notify(err.message)}finally{b.disabled=false}};return}app.innerHTML=`<section class="entry"><div><p class="eyebrow">TANÁRI IRÁNYÍTÓPULT</p><h1>Egy terem.<br><em>Sok felfedező.</em></h1><p class="intro">Te indítod a küldetéseket. A telefonokon születnek a megoldások, a kivetítőn összeérnek az eredmények.</p>${art()}</div><div class="card"><span class="pill">Első kipróbálható változat</span><h2 style="margin-top:24px">Indulhat az új csoport?</h2><p>Minden játék saját belépőkódot és ranglistát kap. Legfeljebb 50 játékos csatlakozhat.</p><button id="create" class="primary">Új játék létrehozása →</button><p class="demo-note">Minden csoport külön játékban vesz részt. A játékkód 24 óráig érvényes.</p></div></section>`;bind('#create',create)}
async function create(){if(state&&!['closed','finished'].includes(state.status)&&!confirm('Lezárod a jelenlegi játékot és új csoportot indítasz?'))return;if(state&&!['closed','finished'].includes(state.status))await control('close');const r=await api('create',{admin});code=r.code;token=r.token;sessionStorage.setItem('kando-nyiltnap-host',JSON.stringify(r));renderKey='';await poll()}
async function control(action){await api('control',{code,token,action});await poll()}
function roster(limit=50,offset=0){return state.players.slice(offset,offset+limit).map((p,i)=>`<div class="person ${p.me?'me':''} ${p.done?'done':''}"><span class="place">${i+offset+1}</span><span class="avatar">${icons[p.avatar]}</span><strong>${esc(p.name)}</strong><span class="points">${p.score}</span></div>`).join('')||'<div class="empty">A csatlakozó játékosok itt jelennek meg.</div>'}
const phaseName=()=>({lobby:'Csatlakozás',playing:'Küldetés folyamatban',results:'Köreredmény',finished:'Küldetés teljesítve',closed:'Játék lezárva'})[state.status];
function host(){rosterPage=Math.min(rosterPage,Math.max(0,Math.ceil(state.players.length/8)-1));const r=state.rounds[state.round],done=state.players.filter(p=>p.done).length;
app.innerHTML=`<section class="host"><div class="host-top"><div><p class="eyebrow">TANÁRI IRÁNYÍTÓPULT</p><h1>${phaseName()}</h1><span class="pill">${state.players.length} / 50 játékos</span></div><div class="row"><button class="secondary" id="project">Kivetítő megnyitása ↗</button><button class="secondary" id="demo">Próbajátékos ↗</button><button class="secondary" id="new">Új csoport</button></div></div><div class="host-grid"><div class="card"><p class="eyebrow">${state.status==='lobby'?'CSATLAKOZÁSI KÓD':'JÁTÉK'} / ${esc(code)}</p>${state.status==='lobby'?`<div class="code">${code.slice(0,3)} ${code.slice(3)}</div><p>Telefonon vagy iPaden nyisd meg:</p><p class="join-link">${esc(state.joinUrl)}</p>`:`<h2>${r?esc(r.title):'Szép munka, csapat!'}</h2><p>${r?esc(r.brief):'Minden küldetés véget ért. Jöhet a közös megbeszélés!'}</p>${state.status==='playing'?`<div class="row spread"><span class="timer">${timeText()}</span><b>${done} / ${state.players.length} kész</b></div>`:''}`}<div class="mission-list">${state.rounds.map((x,i)=>`<div><b>${i<state.round||state.status==='finished'?'✓':String(i+1).padStart(2,'0')}</b><span>${esc(x.title)}<small>${x.field}</small></span></div>`).join('')}</div><div class="host-actions">${state.status==='lobby'?'<button id="next" class="primary">Játék indítása →</button>':state.status==='results'?`<button id="next" class="primary">${state.round===2?'Végeredmény →':'Következő küldetés →'}</button>`:state.status==='playing'?`<button id="pause" class="secondary">${state.paused?'Folytatás':'Szünet'}</button><button id="end" class="primary">Kör lezárása →</button>`:''}<button id="close" class="danger">Játék bezárása</button></div><p class="demo-note">A „Próbajátékos” új ablakban nyílik meg. Kivetítéshez húzd át a közönségnézetet a projektorra.</p></div><div class="card"><div class="row spread"><h2>Élő ranglista</h2><span class="muted">Pontosság számít, nem a telefon sebessége.</span></div><div class="roster">${roster(8,rosterPage*8)}</div>${state.players.length>8?`<div class="row spread" style="margin-top:12px"><button class="secondary" id="rank-prev" ${rosterPage===0?'disabled':''}>←</button><span>${rosterPage+1} / ${Math.ceil(state.players.length/8)}</span><button class="secondary" id="rank-next" ${(rosterPage+1)*8>=state.players.length?'disabled':''}>→</button></div>`:''}</div></div></section>`;
bind('#rank-prev',()=>{rosterPage--;host()});bind('#rank-next',()=>{rosterPage++;host()});bind('#new',create);bind('#next',()=>control('next'));bind('#pause',()=>control('pause'));bind('#end',()=>control('end'));bind('#close',()=>{if(confirm('Lezárod a játékot? A kóddal már nem lehet majd belépni.'))return control('close')});bind('#project',()=>window.open(pageURL('?view=screen&code='+code),'kando-screen'));bind('#demo',()=>window.open(pageURL('?code='+code),'kando-nyiltnap-player'))}
function timeText(){return state.paused?'SZÜNET':Math.floor(state.remaining/60)+':'+String(state.remaining%60).padStart(2,'0')}
function screen(){const r=state.rounds[state.round],done=state.players.filter(p=>p.done).length;app.innerHTML=`<section class="projector"><div class="row spread"><p class="eyebrow">${state.status==='lobby'?'CSATLAKOZZ A KÜLDETÉSHEZ':phaseName().toUpperCase()}</p><span class="pill">${state.players.length} felfedező</span></div><div class="screen-grid"><div>${state.status==='lobby'?`<h1>Most te jössz.<br>Kapcsolódj be!</h1><p class="join-link">${esc(state.joinUrl)}</p><div class="code">${code.slice(0,3)} ${code.slice(3)}</div><p class="screen-note">Nyisd meg az oldalt, és írd be a játékkódot!</p>`:state.status==='finished'||state.status==='closed'?`<div class="celebrate">✦</div><h1>Szép munka,<br>felfedezők!</h1><p class="screen-note">Bekötöttétek. Megírtátok. Leteszteltétek.</p>`:`<h1>${esc(r.title)}</h1><p class="screen-note">${esc(r.brief)}</p>${state.status==='playing'?`<span class="timer">${timeText()}</span><div class="completion">${done}<small style="font-size:28px"> / ${state.players.length}</small></div><p class="screen-note">megoldott küldetés</p><div class="progress-track"><i style="width:${done/Math.max(1,state.players.length)*100}%"></i></div>`:'<p class="screen-note">A következő kört a tanár indítja.</p>'}`}</div><div class="card"><p class="eyebrow">${state.status==='lobby'?'MÁR ITT VAGYUNK':'AZ ÉLMEZŐNY'}</p><div class="roster">${roster(8)}</div>${state.players.length>8?`<p class="muted" style="margin:15px 0 0">+ ${state.players.length-8} játékos · a teljes ranglista a tanári képernyőn</p>`:''}</div></div></section>`}
function resetPlayer(){sessionStorage.removeItem('kando-nyiltnap-player');token='';code='';state=null;view='join';renderKey='';history.replaceState(null,'',pageURL(''));entry()}
function playerWaiting(){const p=state.self;if(!p){resetPlayer();return}app.innerHTML=`<section class="waiting"><div class="avatar-big">${icons[p.avatar]}</div><p class="eyebrow">${phaseName().toUpperCase()}</p><h1>${state.status==='lobby'?`Szia, ${esc(p.name)}!`:state.status==='finished'?'Ez a te eredményed!':state.status==='closed'?'Találkozunk legközelebb!':p.done?'Megoldottad!':'Ez a kör véget ért.'}</h1>${state.status==='lobby'?`<p>Bent vagy a <b>${code}</b> játékban.<br>A tanár hamarosan elindítja az első küldetést.</p><span class="pill">${state.players.length} játékos csatlakozott</span>`:`<div class="result-score">${p.score} <small style="font-size:18px">pont</small></div><p>${state.status==='finished'?'Hálózatépítő, programozó és hibavadász is voltál. Melyik tetszett a legjobban?':state.status==='closed'?'A csoport játéka lezárult.':state.status==='playing'?'A többiek még dolgoznak. Nézz fel a kivetítőre!':'A következő küldetést a tanár indítja.'}</p><div class="roster">${roster(5)}</div>`}${['finished','closed'].includes(state.status)?'<button id="reset-player" class="primary" style="margin-top:24px">Következő játékos →</button>':''}</section>`;bind('#reset-player',resetPlayer)}
function plug(type){const shape=type==='lan'?'<path d="M12 6h24v23l-7 8H19l-7-8z" fill="#aac5d5"/><path d="M17 10v10m5-10v10m5-10v10m5-10v10" stroke="#ecc67f" stroke-width="3"/><path d="M19 26h10v13H19z" fill="#43889a"/>':type==='hdmi'?'<path d="M5 10h38v15l-8 9H13l-8-9z" fill="#cad4e5"/><path d="M10 15h28v8H10z" fill="#c9a96f"/><path d="M16 34h16v8H16z" fill="#7288a4"/>':'<path d="M19 4h10v20H19z" fill="#d8e4ea"/><path d="M17 12h14v4H17z" fill="#47505f"/><rect x="15" y="24" width="18" height="18" rx="4" fill="#8490a0"/>';return `<svg viewBox="0 0 48 48" aria-hidden="true">${shape}</svg>`}
function game(){task={answer:{},selected:null,program:[],robot:[0,3],quantity:1,printed:false,choice:null,running:false};const r=state.rounds[state.round];app.innerHTML=`<section class="game"><div class="game-top"><div><p class="eyebrow">${state.round+1} / 3 · ${r.field}</p><h1>${esc(r.title)}</h1></div><span class="timer" id="timer">${timeText()}</span></div><p class="brief">${esc(r.brief)}</p><div class="game-meta"><span>${esc(state.self.name)}</span><span>${state.self.score} pont</span></div><div class="workspace" id="workspace"></div><div class="feedback" id="feedback" role="status"></div><div class="game-footer"><p class="hint" id="hint">${state.round===0?'Bökj egy kábelre, majd a TV-box megfelelő aljzatára.':state.round===1?'A nyilakkal építs programot. A lila blokkokra bökve törölhetsz.':'Ne csak tippelj: kérj több jegyet, és nézd meg, mit ad a gép!'}</p><button id="check" class="primary">${state.round===1?'▶ Futtatás':'Ellenőrzés →'}</button></div></section>`;if(state.round===0)cables();else if(state.round===1)robot();else tickets();bind('#check',submit);updatePause()}
function feedback(text){if($('#feedback'))$('#feedback').textContent=text}
function cables(){const sources=[['router','lan','Router','Hálózati kábel'],['tv','hdmi','Televízió','Kép és hang'],['power','dc','Tápegység','Áramellátás']];$('#workspace').innerHTML=`<div class="mini-tv ${Object.keys(task.answer).length===3?'live':''}"><span>${Object.keys(task.answer).length===3?'◉ Készen áll a próbára':'TV · Várja a bekötést'}</span></div><div class="cables"><div><p class="device-title">KÁBELEK AZ ESZKÖZÖKTŐL</p><div class="cable-column">${sources.map(([id,type,title,desc])=>`<button data-source="${id}" class="connector ${task.selected===id?'active':''} ${task.answer[id]?'connected':''}">${plug(type)}<span>${title}<small>${task.answer[id]?'→ '+task.answer[id].toUpperCase():desc}</small></span></button>`).join('')}</div></div><div><p class="device-title">TV-BOX · HÁTLAP</p><div class="cable-column">${['hdmi','dc','lan'].map(type=>`<button data-port="${type}" class="connector ${Object.values(task.answer).includes(type)?'connected':''}">${plug(type)}<span>${type==='hdmi'?'HDMI OUT':type==='dc'?'DC IN':'LAN'}<small>${type==='hdmi'?'Digitális kép és hang':type==='dc'?'Tápfeszültség':'Hálózat'}</small></span></button>`).join('')}</div></div></div>`;document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{task.selected=b.dataset.source;cables()});document.querySelectorAll('[data-port]').forEach(b=>b.onclick=()=>{if(!task.selected){feedback('Előbb válassz egy kábelt a bal oldalon!');return}for(const id in task.answer)if(task.answer[id]===b.dataset.port)delete task.answer[id];task.answer[task.selected]=b.dataset.port;task.selected=null;feedback('A kábel a helyén. Bármelyiket átkötheted.');cables()})}
function robot(){const directions={U:'↑',R:'→',D:'↓',L:'←'};$('#workspace').innerHTML=`<div class="robot-layout"><div class="board">${Array.from({length:16},(_,i)=>{const x=i%4,y=Math.floor(i/4),wall=[[1,2],[2,2],[2,0]].some(p=>p[0]===x&&p[1]===y),bot=task.robot[0]===x&&task.robot[1]===y,goal=x===3&&y===0;return `<div class="cell ${wall?'wall':''} ${goal?'goal':''} ${bot?'bot':''}" aria-label="${bot?'Robot':wall?'Akadály':goal?'Cél':'Szabad mező'}">${bot?'▣':wall?'×':goal?'✦':''}</div>`}).join('')}</div><div class="robot-controls"><p class="device-title">A TE PROGRAMOD · ${task.program.length} / 12</p><div class="program">${task.program.map((d,i)=>`<button class="block" data-remove="${i}" aria-label="${i+1}. lépés törlése" ${task.running?'disabled':''}>${directions[d]}</button>`).join('')}</div><div class="arrows">${Object.entries(directions).map(([d,s])=>`<button data-dir="${d}" aria-label="${({U:'Fel',R:'Jobbra',D:'Le',L:'Balra'})[d]}" ${task.running?'disabled':''}>${s}</button>`).join('')}</div><button class="secondary" id="clear-program" ${task.running?'disabled':''}>Törlés</button></div></div>`;document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>{if(task.program.length<12){task.program.push(b.dataset.dir);task.robot=[0,3];robot()}else feedback('Legfeljebb 12 lépést használj!')});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{task.program.splice(+b.dataset.remove,1);task.robot=[0,3];robot()});bind('#clear-program',()=>{task.program=[];task.robot=[0,3];robot()})}
function tickets(){const options=[['price','A jegyek árát rosszul számolja.'],['quantity','A kért darabszám helyett mindig egy jegyet ad.'],['button','A + gomb csökkenti a darabszámot.']];$('#workspace').innerHTML=`<div class="ticket-layout"><div class="machine"><h3>KANDÓ EXPRESSZ<br><small>1 jegy = 300 Ft</small></h3><div class="counter"><button id="minus" aria-label="Kevesebb jegy">−</button><b>${task.quantity}</b><button id="plus" aria-label="Több jegy">+</button></div><p class="total">Összesen: ${task.quantity*300} Ft</p><button class="print" id="print">Jegyek kiadása</button><div class="ticket-output">${task.printed?'<span class="ticket">▥ KANDÓ EXPRESSZ · 1 db jegy</span>':'<small>Itt jelennek meg a jegyek</small>'}</div></div><div><p class="device-title">MELYIK HIBÁT TAPASZTALTAD?</p><div class="bug-options">${options.map(([id,text])=>`<button data-bug="${id}" class="${task.choice===id?'selected':''}">${text}</button>`).join('')}</div></div></div>`;bind('#plus',()=>{task.quantity=Math.min(4,task.quantity+1);task.printed=false;tickets()});bind('#minus',()=>{task.quantity=Math.max(1,task.quantity-1);task.printed=false;tickets()});bind('#print',()=>{task.printed=true;if(task.quantity>1)task.tested=true;tickets()});document.querySelectorAll('[data-bug]').forEach(b=>b.onclick=()=>{task.choice=b.dataset.bug;tickets()})}
async function submit(){if(task.running)return;let answer;if(state.round===0){answer=task.answer;if(Object.keys(answer).length!==3){feedback('Mindhárom kábelt kösd be!');return}}else if(state.round===2){if(!task.tested){feedback('Tesztelj egy másik esetet is: kérj 2 vagy több jegyet!');return}if(!task.choice){feedback('Válaszd ki, milyen hibát találtál!');return}answer=task.choice}else{answer=[...task.program];if(!answer.length){feedback('Előbb adj legalább egy utasítást a robotnak!');return}}
const currentRound=state.round,currentTask=task;$('#check').disabled=true;task.running=true;
try{if(currentRound===1){task.robot=[0,3];for(const d of answer){if(state.paused||state.status!=='playing'||task!==currentTask){feedback('A futás megszakadt. Folytatás után újra elindíthatod.');return}const [dx,dy]=({U:[0,-1],D:[0,1],L:[-1,0],R:[1,0]})[d];const x=task.robot[0]+dx,y=task.robot[1]+dy;if(x<0||x>3||y<0||y>3||[[1,2],[2,2],[2,0]].some(p=>p[0]===x&&p[1]===y))break;task.robot=[x,y];robot();await new Promise(r=>setTimeout(r,280))}}
const r=await api('answer',{code,token,round:currentRound,answer});if(r.correct){notify(`Megoldottad! +${r.points} pont`);await poll()}else feedback(currentRound===0?'Még nem jó az összekötés. Nézd meg a csatlakozók alakját és feliratát!':currentRound===1?'A robot nem ért célba. Kerüld meg az akadályokat, és próbáld újra!':'Ez a funkció jól működik. Hasonlítsd össze a kért és a kiadott jegyek számát!')
}finally{currentTask.running=false;if(task===currentTask&&$('#check')){if(currentRound===1)robot();$('#check').disabled=false}}}
function updatePause(){if($('#timer'))$('#timer').textContent=timeText();let layer=$('.pause-overlay');if(state.paused&&!layer&&view==='player'){layer=document.createElement('div');layer.className='pause-overlay';layer.innerHTML='<div><p class="eyebrow">RÖVID PIHENŐ</p><h2>A tanár szünetelteti a játékot.</h2><p>A megoldásod megmarad.</p></div>';document.body.append(layer)}else if(!state.paused&&layer)layer.remove()}
async function poll(){if(!code||polling)return;polling=true;try{const res=await fetch(apiURL('state?code='+encodeURIComponent(code)),{cache:'no-store',headers:token?{Authorization:'Bearer '+token}:{}});const d=await res.json();if(!res.ok){if(res.status===404){code='';token='';state=null;renderKey='';if(view==='host'){sessionStorage.removeItem('kando-nyiltnap-host');hostStart()}else if(view==='player'){resetPlayer()}else{app.innerHTML='<section class="waiting"><h1>A játék már nem érhető el.</h1><p>Nyisd meg az új kivetítőnézetet a tanári felületről.</p></section>'}notify(d.error);return}throw Error(d.error)}state=d;$('.reconnect')?.remove();if(view==='host'){const key=JSON.stringify([d.status,d.round,d.paused,d.players]);if(key!==renderKey){renderKey=key;host()}else if($('.timer'))$('.timer').textContent=timeText()}else if(view==='screen'){const key=JSON.stringify([d.status,d.round,d.paused,d.players]);if(key!==renderKey){renderKey=key;screen()}else if($('.timer'))$('.timer').textContent=timeText()}else if(view==='player'){const active=d.status==='playing'&&!d.self?.done;const key=[d.status,d.round,d.self?.done,active].join('|');if(key!==renderKey){renderKey=key;if(active)game();else playerWaiting()}updatePause()}}catch(e){if(!$('.reconnect')){const banner=document.createElement('div');banner.className='reconnect';banner.textContent='Kapcsolódás… Ellenőrizd az internetkapcsolatot. A játékodhoz automatikusan visszakapcsolódunk.';document.body.append(banner)}}finally{polling=false}}
if(view==='host'){code?poll():hostStart()}else if(view==='screen'){if(code)poll();else app.innerHTML='<section class="waiting"><h1>A kivetítőt a tanári felületről nyisd meg.</h1></section>'}else if(view==='player')poll();else entry();
setInterval(poll,1200);
